Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "debian_#{i}" do |deb|
      deb.vm.box = "debian/bullseye64"
      deb.vm.network "public_network", bridge: "wlan0"

      deb.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
      end
    end
  end
end
