Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "public_network", bridge: "wlan0"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
    v.name = "apache-instance"
  end

  # Configurando o provisionamento baseado na execução de um shellscript
  config.vm.provision "shell", path: "apache.sh"

end
