Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
    v.name = "vagrant-shell"
  end
  
  # Executando comando de atualização de repositórios sempre que a máquina for inicializada
  config.vm.provision "shell", inline: "sudo apt update"

end
